version: '3.1'
services:
  dataflow_templates:
    container_name: dataflow_templates
    image: dataflow_templates:dev
    ports:
      - "9444:8080"
    volumes:
      - ./:/app:delegated

      # The below volume stores your container's bash history between container runs
      - ./.container_bash_history:/root/.bash_history
    env_file: .env
