steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_TEMPLATE_IMAGE"
      - "--file=Dockerfile"
      - .
    id: Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "${_TEMPLATE_IMAGE}"
    id: Docker Push
  - name: "ubuntu"
    args: ["bash", "-c", "date -u +%F_%T > _TIMESTAMP"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - dataflow
      - "flex-template"
      - build
      - "${_TEMPLATE_BUCKET}/$(cat _TIMESTAMP)/${_TEMPLATE_NAME}"
      - "--image"
      - "${_TEMPLATE_IMAGE}"
      - "--sdk-language"
      - "PYTHON"
      - "--metadata-file"
      - "src/main/python/template/metadata.json"
      - "--enable-streaming-engine"
    entrypoint: gcloud
    id: Build Template
timeout: 900s
images:
  - "$_TEMPLATE_IMAGE"
options:
  substitutionOption: ALLOW_LOOSE
  dynamic_substitutions: true
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _ARTIFACT_PROJECT_ID: "gs-development-168620"
  _TEMPLATE_IMAGE: "${_GCR_HOSTNAME}/${_ARTIFACT_PROJECT_ID}/${REPO_NAME}/dataflow-flex-template:${COMMIT_SHA}"
  _TEMPLATE_BUCKET: "gs://custom_dataflow_templates/cloudbuild"
  _TEMPLATE_NAME: "PubSub_Avro_To_BigQuery"

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - dataflow-template
